### ISSUE TITLE
Sub app creation issue

### ISSUE THREAD

**Issue by ruwhan** [yoannmoinet/generator-maryeo#2]
Hi, I got this when try to create a sub app named _core_. 

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at MaryoGenerator.writing.app (/Users/ruwhan/npm/lib/node_modules/generator-maryeo/generators/subapp/index.js:63:51)
    at /Users/ruwhan/npm/lib/node_modules/generator-maryeo/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

EDIT: I've tried using node v4.0.0 & v0.10

Thanks,

PS: great generator btw. :+1:

**Comment by yoannmoinet** [comment]
Thanks, I'll look into this.

Be aware that there are some sub-generators that lead nowhere.
But the general scaffold should be working good.

**Comment by ruwhan** [comment]
@yoannmoinet thanks, as more info, it only happen when I generate from `Yeoman` menu, **not** `yo maryeo` command.
